apiVersion: v1
kind: Service
metadata:
  name: uiapp-service
spec:
  selector:
    app: uiapp         #Must match the pod label
  ports:
    - port: 80            #This is the service port
      targetPort: 80      #This is the container port
  type: LoadBalancer        #type of service